name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file server/Dockerfile --tag gcr.io/storemaven-375719/tap-game-backend:$(date +%s)
      

    - name: Push Docker Image to GCR
      # You may pin to the exact commit or the version.
      # uses: kurkop/push-docker-gcr@4ee82fa6b080179896960dd11b04c766be5ba39d
      uses: kurkop/push-docker-gcr@v1.2.2
      with:
        docker_image_name: tap-game-backend
        docker_image_tag: $(date +%s)
        dockerfile: server/Dockerfile
        gcr_host: gcr.io
        gcr_project_id: storemaven-375719
        gcr_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}