name: Backend CI

on:
  push:
    branches: [ "dev" ]


jobs:
  build:

    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/prod-deploy')

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: server/
      run: docker build . --file Dockerfile --tag gcr.io/storemaven-375719/tap-game-backend:5
      

    - name: Push Docker Image to GCR
      uses: kurkop/push-docker-gcr@v1.2.2
      with:
        docker_image_name: tap-game-backend
        docker_image_tag: 5
        dockerfile: server/Dockerfile
        gcr_host: gcr.io
        gcr_project_id: storemaven-375719
        gcr_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}